version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: buffbyte_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: buffer_lyte
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - buffbyte_network

  # Mongo Express (MongoDB UI)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: buffbyte_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - buffbyte_network

volumes:
  mongodb_data:
    driver: local

networks:
  buffbyte_network:
    driver: bridge
